name: Morning-Tweet
on:
  schedule:
    - cron: '0 9 * * *'      # 09:00 UTC  / 10:00 UK summer
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install tweepy
        run: pip install tweepy
      - name: Run tweet.py
        env:
          API_KEY:        ${{ secrets.API_KEY }}
          API_SECRET:     ${{ secrets.API_SECRET }}
          ACCESS_TOKEN:   ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET:  ${{ secrets.ACCESS_SECRET }}
          BEARER_TOKEN:   ${{ secrets.BEARER_TOKEN }}
        run: python tweet.py
